name: dev-build
description: dev-build action for the pipeline

inputs:
  SERVICE_ACCOUNT_KEYFILE_JSON:
    description: dev env's service account keyfile json
    required: true

  ARTIFACTORY_USER:
    description: App's Artifactory user name
    required: true
  
  ARTIFACTORY_PASS:
    description: App's Artifactory passcode
    required: true

  CLIENT_ID:
    description: dev env's Cliend ID
    required: true

  CLIENT_SECRET:
    description: dev env's Client Secret
    required: true


runs:
  using: "composite"

  steps:
  - name: Condition...
    run: |
      if [ ${{inputs.ARTIFACTORY_PASS}} == "Welcome23@02023$" ]; then
        echo "Same"
      else
        echo "Not same"
      fi
      
  
