name: dev Runner

on: workflow_dispatch

jobs:
  deployment:
    environment: dev
    runs-on: ubuntu-latest
    container: node:16-alpine

    steps:
    - name: Checking out repo...
      uses: actions/checkout@v3
      
    - name: Content...
      run: |
        echo "${{ vars.username }}"
        echo "${{ vars.password }}"
