name: dev Runner

on: workflow_dispatch

jobs:
  deployment:
    environment: dev
    runs-on: ubuntu-latest
    container: node:16-alpine

    steps:
    - name: Checking out repo...
      uses: actions/checkout@v3
      
    - name: Content...
      run: |
        echo "${{ vars.username }}"
        echo "${{ vars.password }}"

    - name: Condition...
      run: |
        if [ ${{secrets.ARTIFACTORY_PASS}} == ${{vars.password}} ]; then
          echo "Same"
        else
          echo "Not same"
        fi

    - name: Building...
      uses: ./.github/actions/dev-build
      with:
        SERVICE_ACCOUNT_KEYFILE_JSON: ${{ secrets.SERVICE_ACCOUNT_KEYFILE_JSON }}
        ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
        ARTIFACTORY_PASS: ${{ secrets.ARTIFACTORY_PASS }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    
    - name: Deploying...
      uses: ./.github/actions/dev-deploy

